<?php

/**
 * PluginPointSettingTable
 * @package    opPoint2Plugin
 * @subpackage model
 * @author     Hiromi Hishida <info@77-web.com>
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPointSettingTable extends Doctrine_Table
{

}