<?php

/**
 * PluginPoint
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opPoint2Plugin
 * @subpackage model
 * @author     Hiromi Hishida <info@77-web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPoint extends BasePoint
{
  public function preInsert($event)
  {
    $event->getInvoker()->setRestPoints($event->getInvoker()->getPoints());
    if(0 < $event->getInvoker()->getPoints())
    {
      $event->getInvoker()->setExpiresAt(date('Y-m-d', time() + 60*60*24*sfConfig::get('app_point_expire_days', 365)));
    }
  }
}