<?php

/**
 * PluginPointSetting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opPoint2Plugin
 * @subpackage model
 * @author     Hiromi Hishida <info@77-web.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginPointSetting extends BasePointSetting
{

}